import { describe, expect, it } from "vitest";
import {
  buildModuleContribution,
  renderEnvironmentYml,
  renderNfTest,
} from "../src/composition/contribution.js";
import type { LocalToolSpec } from "../src/composition/localModule.js";

const spec: LocalToolSpec = {
  name: "myfilter",
  toolName: "myfilter",
  description: "Filters a BAM by a custom rule.",
  command: "myfilter --in $bam --out ${prefix}.filtered.bam",
  conda: "bioconda::samtools=1.19",
  inputs: [{ name: "bam", type: "file" }],
  outputs: [{ name: "bam", type: "file", pattern: "*.filtered.bam" }],
  versionCommand: "myfilter --version",
  hasMeta: true,
};

describe("renderEnvironmentYml", () => {
  it("uses the declared conda dependency", () => {
    const env = renderEnvironmentYml(spec);
    expect(env).toContain("bioconda::samtools=1.19");
    expect(env).toContain("channels:");
    expect(env).toContain("- bioconda");
  });

  it("leaves a TODO when no conda dependency is set", () => {
    const env = renderEnvironmentYml({ ...spec, conda: undefined });
    expect(env).toContain("TODO");
  });
});

describe("renderNfTest", () => {
  it("is an nf-test targeting the process with tags and a stub test", () => {
    const t = renderNfTest(spec);
    expect(t).toContain('process "MYFILTER"');
    expect(t).toContain('tag "modules"');
    expect(t).toContain('tag "myfilter"');
    expect(t).toContain('options "-stub"');
    expect(t).toContain("snapshot(process.out).match()");
  });
});

describe("buildModuleContribution", () => {
  const c = buildModuleContribution(spec);

  it("lays files out under modules/nf-core/<name>", () => {
    expect(c.moduleDir).toBe("modules/nf-core/myfilter");
    expect(Object.keys(c.files).sort()).toEqual([
      "modules/nf-core/myfilter/environment.yml",
      "modules/nf-core/myfilter/main.nf",
      "modules/nf-core/myfilter/meta.yml",
      "modules/nf-core/myfilter/tests/main.nf.test",
    ]);
  });

  it("omits the Hirsh generator comment from the contributed main.nf", () => {
    const main = c.files["modules/nf-core/myfilter/main.nf"];
    expect(main).not.toContain("generated by Hirsh");
    expect(main.startsWith("process MYFILTER {")).toBe(true);
  });
});
