import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";
import {
  buildSynthesizedDefinition,
  definitionFileName,
  renderDefinitionYaml,
  type DefinitionSource,
} from "../src/pipelines/synthDefinition.js";
import type { SynthesizedSpec } from "../src/pipelines/nfcoreSchema.js";

const SOURCE: DefinitionSource = {
  fullName: "nf-core/atacseq",
  description: "ATAC-seq peak-calling and QC analysis pipeline",
  topics: ["atac-seq", "chromatin-accessibility"],
  revision: "2.1.2",
  url: "https://nf-co.re/atacseq",
};

const SPEC: SynthesizedSpec = {
  params: [
    { name: "aligner", kind: "enum", required: true, choices: ["bwa", "bowtie2"], default: "bwa", description: "Aligner.", reference: false },
    { name: "fasta", kind: "file", required: false, description: "Genome FASTA.", reference: true },
    { name: "genome", kind: "string", required: false, description: "iGenomes key.", reference: true },
  ],
  columns: [
    { name: "sample", required: true, isFile: false },
    { name: "fastq_1", required: true, isFile: true },
    { name: "fastq_2", required: false, isFile: true },
    { name: "replicate", required: true, isFile: false },
  ],
};

describe("buildSynthesizedDefinition", () => {
  const def = buildSynthesizedDefinition(SOURCE, SPEC);

  it("carries name, pinned revision, and a test profile", () => {
    expect(def.name).toBe("nf-core/atacseq");
    expect(def.version).toBe("2.1.2");
    expect(def.profiles).toEqual({ recommended: "docker", hasTestProfile: true, testProfile: "test" });
  });

  it("prepends input (samplesheet-provided) and outdir, then schema params", () => {
    const names = def.params.map((p) => p.name);
    expect(names.slice(0, 2)).toEqual(["input", "outdir"]);
    expect(def.params.find((p) => p.name === "input")?.providedBySamplesheet).toBe(true);
    const aligner = def.params.find((p) => p.name === "aligner");
    expect(aligner).toMatchObject({ type: "enum", required: true, choices: ["bwa", "bowtie2"], default: "bwa" });
    // file/directory params map to the "path" type.
    expect(def.params.find((p) => p.name === "fasta")?.type).toBe("path");
  });

  it("maps the samplesheet columns from the input schema", () => {
    expect(def.samplesheet.columns.map((c) => c.name)).toEqual([
      "sample",
      "fastq_1",
      "fastq_2",
      "replicate",
    ]);
    expect(def.samplesheet.columns.find((c) => c.name === "replicate")?.required).toBe(true);
  });

  it("infers a FASTQ data type and derives useWhen from topics", () => {
    expect(def.dataType).toMatch(/FASTQ/);
    expect(def.useWhen.join(" ")).toMatch(/atac seq/i);
  });

  it("leaves results as a single generic directory to refine", () => {
    expect(def.results.outdirParam).toBe("outdir");
    expect(def.results.outputs).toHaveLength(1);
    expect(def.results.outputs[0]).toMatchObject({ path: ".", kind: "directory" });
  });

  it("produces a definition that satisfies the registry's validation contract", () => {
    // Mirrors registry.ts::validate — a generated definition must be loadable.
    for (const key of ["name", "version", "title", "purpose", "samplesheet", "params", "profiles", "results"]) {
      expect((def as Record<string, unknown>)[key]).toBeDefined();
    }
    expect(Array.isArray(def.params)).toBe(true);
    expect(typeof def.results.outdirParam).toBe("string");
  });
});

describe("renderDefinitionYaml", () => {
  it("round-trips through YAML with a provenance header", () => {
    const def = buildSynthesizedDefinition(SOURCE, SPEC);
    const yaml = renderDefinitionYaml(def, "2026-07-07");
    expect(yaml).toMatch(/^# Auto-generated by Hirsh/);
    expect(yaml).toMatch(/NOT hand-curated/);
    const parsed = parseYaml(yaml);
    expect(parsed.name).toBe("nf-core/atacseq");
    expect(parsed.params.find((p: { name: string }) => p.name === "aligner").choices).toEqual(["bwa", "bowtie2"]);
  });
});

describe("definitionFileName", () => {
  it("makes a file-safe name from the pipeline id", () => {
    expect(definitionFileName("nf-core/atacseq")).toBe("nf-core-atacseq.yaml");
    expect(definitionFileName("nf-core/scrnaseq")).toBe("nf-core-scrnaseq.yaml");
  });
});
