/**
 * Assisted contribution to nf-core/modules (Phase 5).
 *
 * Turns a local (custom) tool into a module laid out the way nf-core/modules
 * expects — `main.nf`, `meta.yml`, `environment.yml` and an `nf-test` — so a
 * scientist can review it and open a PR. This module only *prepares* the files;
 * opening the PR is a deliberate, human-in-the-loop step (nf-core acceptance is a
 * community decision, not something the agent can or should force).
 *
 * Renderers are pure; writeContribution touches disk.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { processName } from "../modules/types.js";
import { renderLocalMeta, renderLocalModuleMain, type LocalToolSpec } from "./localModule.js";

/** conda `environment.yml` for the module (nf-core requires one). */
export function renderEnvironmentYml(spec: LocalToolSpec): string {
  const dep = spec.conda ?? `# TODO: add a bioconda/conda-forge dependency, e.g. bioconda::${spec.toolName}=<version>`;
  return `name: ${spec.name}
channels:
  - conda-forge
  - bioconda
dependencies:
  - ${dep}
`;
}

/** A minimal nf-test that exercises the module's stub path. */
export function renderNfTest(spec: LocalToolSpec): string {
  const proc = processName(spec.name);
  const hasMeta = spec.hasMeta !== false;
  const input = hasMeta
    ? `                input[0] = [\n                    [ id:'test' ],\n                    file(params.modules_testdata_base_path + 'genomics/sarscov2/illumina/bam/test.paired_end.bam', checkIfExists: true)\n                ]`
    : `                input[0] = file(params.modules_testdata_base_path + 'genomics/sarscov2/illumina/bam/test.paired_end.bam', checkIfExists: true)`;
  return `// Generated by Hirsh — review and adjust the test inputs for real data.
nextflow_process {

    name "Test Process ${proc}"
    script "../main.nf"
    process "${proc}"

    tag "modules"
    tag "modules_nfcore"
    tag "${spec.name}"

    test("${spec.name} - stub") {

        options "-stub"

        when {
            process {
                """
${input}
                """
            }
        }

        then {
            assertAll(
                { assert process.success },
                { assert snapshot(process.out).match() }
            )
        }
    }
}
`;
}

export interface ContributionFiles {
  /** Repo-relative directory, e.g. "modules/nf-core/myfilter". */
  moduleDir: string;
  /** Map of repo-relative path → file contents. */
  files: Record<string, string>;
}

/** Builds the nf-core/modules file set for a local tool (pure). */
export function buildModuleContribution(spec: LocalToolSpec): ContributionFiles {
  const moduleDir = `modules/nf-core/${spec.name}`;
  const files: Record<string, string> = {
    [`${moduleDir}/main.nf`]: renderLocalModuleMain(spec, { header: null }),
    [`${moduleDir}/meta.yml`]: renderLocalMeta(spec),
    [`${moduleDir}/environment.yml`]: renderEnvironmentYml(spec),
    [`${moduleDir}/tests/main.nf.test`]: renderNfTest(spec),
  };
  return { moduleDir, files };
}

export interface ContributionResult {
  dir: string;
  files: string[];
}

/**
 * Writes the contribution files under `baseDir/contributions/<name>/`. Returns
 * the base dir and the written repo-relative paths.
 */
export function writeContribution(baseDir: string, spec: LocalToolSpec): ContributionResult {
  const root = join(baseDir, "contributions", spec.name);
  const { files } = buildModuleContribution(spec);
  const written: string[] = [];
  for (const [rel, contents] of Object.entries(files)) {
    const full = join(root, rel);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, contents, "utf8");
    written.push(rel);
  }
  return { dir: root, files: written };
}
