/**
 * Pipeline generator (Phase F4).
 *
 * Turns a resolved composition into an nf-core-structured pipeline project on
 * disk, following nf-core principles by construction:
 *   - real modules installed from the pinned nf-core/modules commit,
 *   - modules.json pinning each module's git SHA (reproducibility),
 *   - channel-type-matched wiring (see wiring.ts) so the pipeline runs,
 *   - reference inputs exposed as params, with dummy data for the test profile,
 *   - nextflow.config with container profiles, resource limits and a MANDATORY
 *     `test` profile, nextflow_schema.json + samplesheet schema, CITATIONS.md,
 *     .nf-core.yml, and versions.yml aggregation.
 *
 * The generated `test` profile is wired to run under `-stub-run` with no edits.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { ModuleRegistry } from "../modules/registry.js";
import type { NfCoreModule } from "../modules/types.js";
import type { CompositionPlan, ResolvedComposition } from "./types.js";
import { renderLocalMeta, renderLocalModuleMain, type LocalToolSpec } from "./localModule.js";
import { buildWorkflow, inputColumn, inputExtension, type InputSpec } from "./wiring.js";

export interface GenerationResult {
  dir: string;
  files: string[];
  warnings: string[];
  referenceParams: string[];
  notes: string[];
  /** What the generated pipeline's input channel carries (reads vs a single file). */
  input: InputSpec;
}

const NF_MIN = "!>=23.04.0";

function renderMainNf(plan: CompositionPlan, input: InputSpec): string {
  const wf = `HIRSH_${plan.pipelineName.toUpperCase()}`;
  const reader = input.reads
    ? `    // Samplesheet reader (columns: sample,fastq_1[,fastq_2]) → [ meta, [ reads ] ].
    ch_input = Channel
        .fromPath(params.input)
        .splitCsv(header: true)
        .map { row ->
            def meta = [ id: row.sample, single_end: !row.fastq_2 ]
            def reads = row.fastq_2 ? [ file(row.fastq_1), file(row.fastq_2) ] : [ file(row.fastq_1) ]
            tuple(meta, reads)
        }`
    : `    // Samplesheet reader (columns: sample,${inputColumn(input.kind)}) → [ meta, ${input.kind} ].
    ch_input = Channel
        .fromPath(params.input)
        .splitCsv(header: true)
        .map { row ->
            tuple([ id: row.sample ], file(row.${inputColumn(input.kind)}))
        }`;
  return `#!/usr/bin/env nextflow
nextflow.enable.dsl = 2

include { ${wf} } from './workflows/${plan.pipelineName}'

workflow {
${reader}

    ${wf}(ch_input)
}
`;
}

function renderNextflowConfig(plan: CompositionPlan, referenceParams: string[]): string {
  const refs = referenceParams.map((p) => `    ${p} = null`).join("\n");
  return `// Auto-generated by Hirsh.
manifest {
    name            = '${plan.pipelineName}'
    description     = ${JSON.stringify(plan.description)}
    nextflowVersion = '${NF_MIN}'
    version         = '0.1.0'
}

params {
    input      = null
    outdir     = 'results'
    max_memory = '128.GB'
    max_cpus   = 16
    max_time   = '240.h'
${refs ? refs + "\n" : ""}}

// Resource ceilings honoured by every process (ties into Hirsh resource-awareness).
process {
    resourceLimits = [
        memory: params.max_memory,
        cpus  : params.max_cpus,
        time  : params.max_time,
    ]
}

profiles {
    docker      { docker.enabled = true }
    singularity { singularity.enabled = true; singularity.autoMounts = true }
    test        { includeConfig 'conf/test.config' }
}
`;
}

function renderTestConfig(referenceParams: string[]): string {
  const refs = referenceParams
    .map((p) => `    ${p} = "\${projectDir}/assets/refs/${p}.txt"`)
    .join("\n");
  return `// Mandatory nf-core-style test profile.
// Uses tiny bundled placeholder data so \`nextflow run . -profile test -stub-run\`
// exercises the whole DAG without real datasets or containers. Replace with real
// small test data for a meaningful functional test.
params {
    input      = "\${projectDir}/assets/samplesheet_test.csv"
    outdir     = 'results_test'
${refs ? refs + "\n" : ""}    max_memory = '6.GB'
    max_cpus   = 2
    max_time   = '2.h'
}
`;
}

function renderModulesJson(plan: CompositionPlan, modules: NfCoreModule[], sha: string): string {
  const modEntries: Record<string, unknown> = {};
  for (const m of modules) {
    modEntries[m.name] = { branch: "master", git_sha: sha, installed_by: ["modules"] };
  }
  const doc = {
    name: plan.pipelineName,
    homePage: "",
    repos: {
      "https://github.com/nf-core/modules.git": { modules: { "nf-core": modEntries } },
    },
  };
  return JSON.stringify(doc, null, 4) + "\n";
}

function renderCitations(modules: NfCoreModule[], localTools: LocalToolSpec[]): string {
  const lines = ["# Citations", "", "## Tools used by this pipeline", ""];
  const seen = new Set<string>();
  for (const m of modules) {
    if (m.local) continue;
    for (const t of m.tools) {
      if (seen.has(t.name)) continue;
      seen.add(t.name);
      const link = t.homepage ? ` (${t.homepage})` : "";
      const doi = t.doi ? ` — doi:${t.doi}` : "";
      lines.push(`- **${t.name}**${link}${doi}`);
    }
  }
  if (localTools.length > 0) {
    lines.push("", "## Custom (local) tools", "");
    for (const t of localTools) {
      lines.push(`- **${t.toolName}** — ${t.description} (local module, not from nf-core)`);
    }
  }
  lines.push("", "nf-core modules sourced from [nf-core/modules](https://github.com/nf-core/modules).", "");
  return lines.join("\n");
}

function renderReadme(plan: CompositionPlan, modules: NfCoreModule[], referenceParams: string[]): string {
  const steps = plan.steps.map((s, i) => `${i + 1}. **${s.module}** — ${s.rationale}`).join("\n");
  const refs = referenceParams.length
    ? `\n## Reference parameters\n\nProvide these for a real run:\n\n${referenceParams
        .map((p) => `- \`--${p}\``)
        .join("\n")}\n`
    : "";
  return `# ${plan.pipelineName}

${plan.description}

> Auto-generated by **Hirsh** from real nf-core modules, with channel-type-matched
> wiring. The \`test\` profile runs under \`-stub-run\` with no edits.

## Steps

${steps}
${refs}
## Run

\`\`\`bash
# structural smoke test (no data/containers needed):
nextflow run . -profile test -stub-run --outdir results_test

# real run:
nextflow run . -profile docker --input samplesheet.csv --outdir results
\`\`\`

## Modules (${modules.length})

${modules.map((m) => `- \`${m.name}\``).join("\n")}
`;
}

function renderInputSchema(input: InputSpec): string {
  const properties: Record<string, unknown> = {
    sample: { type: "string", meta: ["id"], errorMessage: "Sample name is required." },
  };
  let required: string[];
  if (input.reads) {
    properties.fastq_1 = { type: "string", format: "file-path", errorMessage: "fastq_1 path is required." };
    properties.fastq_2 = { type: "string", format: "file-path" };
    required = ["sample", "fastq_1"];
  } else {
    const col = inputColumn(input.kind);
    properties[col] = { type: "string", format: "file-path", errorMessage: `${col} path is required.` };
    required = ["sample", col];
  }
  const doc = {
    $schema: "http://json-schema.org/draft-07/schema",
    title: "Samplesheet validation schema",
    type: "array",
    items: { type: "object", properties, required },
  };
  return JSON.stringify(doc, null, 4) + "\n";
}

function renderPipelineSchema(plan: CompositionPlan, referenceParams: string[]): string {
  const refProps: Record<string, unknown> = {};
  for (const p of referenceParams) {
    refProps[p] = { type: "string", description: `Reference input: ${p}.` };
  }
  const doc = {
    $schema: "http://json-schema.org/draft-07/schema",
    title: `${plan.pipelineName} pipeline parameters`,
    description: plan.description,
    type: "object",
    definitions: {
      input_output_options: {
        title: "Input/output options",
        type: "object",
        required: ["input", "outdir"],
        properties: {
          input: { type: "string", format: "file-path", description: "Path to the samplesheet." },
          outdir: { type: "string", format: "directory-path", description: "Output directory." },
        },
      },
      reference_options: {
        title: "Reference options",
        type: "object",
        properties: refProps,
      },
    },
    allOf: [
      { $ref: "#/definitions/input_output_options" },
      { $ref: "#/definitions/reference_options" },
    ],
  };
  return JSON.stringify(doc, null, 4) + "\n";
}

function renderNfCoreYml(): string {
  return `repository_type: pipeline\nnf_core_version: "generated-by-hirsh"\nlint:\n  files_exist: false\n`;
}

/** Generates the full pipeline project on disk and installs the modules. */
export async function generatePipeline(
  registry: ModuleRegistry,
  resolved: ResolvedComposition,
  baseDir: string,
): Promise<GenerationResult> {
  const { plan, modules, sha } = resolved;
  const localTools = resolved.localTools ?? [];
  const nfcoreModules = modules.filter((m) => !m.local);
  const localModules = modules.filter((m) => m.local);
  const dir = resolve(baseDir, plan.pipelineName);
  const warnings: string[] = [];
  const files: string[] = [];

  const write = (rel: string, contents: string) => {
    const full = join(dir, rel);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, contents, "utf8");
    files.push(rel);
  };

  mkdirSync(dir, { recursive: true });

  // Install each nf-core module from the pinned commit (main.nf required).
  for (const mod of nfcoreModules) {
    const modDir = `modules/nf-core/${mod.name}`;
    try {
      write(`${modDir}/main.nf`, await registry.fetchModuleFile(mod.name, "main.nf"));
    } catch {
      warnings.push(`Could not fetch main.nf for ${mod.name}; the pipeline will not run until fixed.`);
    }
    for (const optional of ["meta.yml", "environment.yml"]) {
      try {
        write(`${modDir}/${optional}`, await registry.fetchModuleFile(mod.name, optional));
      } catch {
        /* not all modules ship every file */
      }
    }
  }

  // Synthesize each local (custom) module — main.nf + meta.yml — from its spec.
  for (const mod of localModules) {
    const spec = localTools.find((t) => t.name === mod.name);
    if (!spec) {
      warnings.push(`No spec for local module ${mod.name}; skipped.`);
      continue;
    }
    write(`modules/local/${mod.name}/main.nf`, renderLocalModuleMain(spec));
    write(`modules/local/${mod.name}/meta.yml`, renderLocalMeta(spec));
  }

  const wiring = buildWorkflow(plan, modules);

  write("main.nf", renderMainNf(plan, wiring.input));
  write(`workflows/${plan.pipelineName}.nf`, wiring.workflow);
  write("nextflow.config", renderNextflowConfig(plan, wiring.referenceParams));
  write("conf/test.config", renderTestConfig(wiring.referenceParams));
  write("nextflow_schema.json", renderPipelineSchema(plan, wiring.referenceParams));
  write("modules.json", renderModulesJson(plan, nfcoreModules, sha));
  write("assets/schema_input.json", renderInputSchema(wiring.input));
  write("CITATIONS.md", renderCitations(modules, localTools));
  write("README.md", renderReadme(plan, modules, wiring.referenceParams));
  write(".nf-core.yml", renderNfCoreYml());

  // --- Dummy test data so `-profile test -stub-run` works with no edits ---
  // Match the placeholder samplesheet to what the input channel actually carries.
  if (wiring.input.reads) {
    const r1 = join(dir, "assets/reads/SAMPLE1_R1.fastq.gz");
    const r2 = join(dir, "assets/reads/SAMPLE1_R2.fastq.gz");
    write("assets/reads/SAMPLE1_R1.fastq.gz", "");
    write("assets/reads/SAMPLE1_R2.fastq.gz", "");
    write("assets/samplesheet_test.csv", `sample,fastq_1,fastq_2\nSAMPLE1,${r1},${r2}\n`);
  } else {
    const col = inputColumn(wiring.input.kind);
    const ext = inputExtension(wiring.input.kind);
    const rel = `assets/input/SAMPLE1.${ext}`;
    write(rel, "");
    write("assets/samplesheet_test.csv", `sample,${col}\nSAMPLE1,${join(dir, rel)}\n`);
  }
  for (const p of wiring.referenceParams) {
    write(`assets/refs/${p}.txt`, "");
  }

  return { dir, files, warnings, referenceParams: wiring.referenceParams, notes: wiring.notes, input: wiring.input };
}
