/**
 * Custom / non-nf-core tools as local modules (Phase 4).
 *
 * A composed pipeline shouldn't be limited to what already exists in nf-core. This
 * turns a scientist's own tool/script into a standards-compliant
 * `modules/local/<name>/main.nf` — the `meta` map convention, a container/conda
 * directive, `versions.yml`, a `when:` guard and a `stub:` block — so it wires
 * into the workflow exactly like an nf-core module (mixing `modules/nf-core/` and
 * `modules/local/`, as real nf-core pipelines do).
 *
 * The renderers are pure (spec in, file text out) so they can be unit-tested; the
 * interactive collector is separated out.
 */
import { processName, type NfCoreModule } from "../modules/types.js";
import type { AgentIO } from "../conversation/io.js";

export interface LocalToolIO {
  /** Element/kind name — drives channel-type wiring, e.g. "bam", "reads", "vcf". */
  name: string;
  /** Data qualifier. */
  type: "file" | "directory" | "string";
  /** Output only: publish glob, e.g. "*.filtered.bam". */
  pattern?: string;
  optional?: boolean;
}

export interface LocalToolSpec {
  /** Module name (lowercase, may contain "/"), e.g. "myfilter". */
  name: string;
  /** Tool name for versions.yml + citations, e.g. "myfilter". */
  toolName: string;
  /** Plain-language description. */
  description: string;
  /** Shell command; Groovy string, so `$prefix` and `$args` are available. */
  command: string;
  /** Container image, e.g. "biocontainers/samtools:1.19--h50ea8bc_0". */
  container?: string;
  /** Conda spec, e.g. "bioconda::samtools=1.19". */
  conda?: string;
  /** nf-core resource label; defaults to "process_single". */
  label?: string;
  /** Whether the process carries a `meta` map (default true). */
  hasMeta?: boolean;
  inputs: LocalToolIO[];
  outputs: LocalToolIO[];
  /** Command that prints the tool version (for versions.yml). */
  versionCommand?: string;
}

/** Turns a publish glob into a concrete stub filename by expanding the first `*`. */
export function globToStubFile(pattern: string, prefixToken: string): string {
  if (!pattern || pattern === "*") return prefixToken;
  if (pattern.includes("*")) return pattern.replace("*", prefixToken);
  return pattern; // literal filename
}

function inputDecl(spec: LocalToolSpec, hasMeta: boolean): string {
  const parts = spec.inputs.map((io) =>
    io.type === "string" ? `val(${io.name})` : `path(${io.name})`,
  );
  if (parts.length === 0) parts.push("path(input)");
  if (hasMeta) return `    tuple val(meta), ${parts.join(", ")}`;
  // Non-meta: declare each input on its own line (nf-core style).
  return parts.map((p) => `    ${p}`).join("\n");
}

function outputDecl(spec: LocalToolSpec, hasMeta: boolean): string {
  const lines = spec.outputs.map((o) => {
    const glob = o.pattern ?? "*";
    return hasMeta
      ? `    tuple val(meta), path("${glob}"), emit: ${o.name}`
      : `    path("${glob}"), emit: ${o.name}`;
  });
  lines.push(`    path "versions.yml", emit: versions`);
  return lines.join("\n");
}

/**
 * Renders the standards-compliant `main.nf` for a local module. `header`
 * overrides the leading comment (pass null to omit it — e.g. for an
 * nf-core/modules contribution, which doesn't carry a generator comment).
 */
export function renderLocalModuleMain(
  spec: LocalToolSpec,
  opts?: { header?: string | null },
): string {
  const proc = processName(spec.name);
  const hasMeta = spec.hasMeta !== false;
  const label = spec.label ?? "process_single";
  const prefixExpr = hasMeta ? `"\${meta.id}"` : `"output"`;
  const versionCmd = spec.versionCommand ?? `echo "0.1.0"`;
  const stubPrefix = "${prefix}";
  const stubTouch = spec.outputs
    .map((o) => `    touch ${globToStubFile(o.pattern ?? "*", stubPrefix)}`)
    .join("\n");

  const conda = spec.conda ? `    conda "${spec.conda}"\n` : "";
  const container = spec.container ? `    container "${spec.container}"\n` : "";
  const noEnv = !spec.conda && !spec.container
    ? "    // NOTE: no container or conda declared — add one for reproducibility.\n"
    : "";

  const headerComment =
    opts?.header === undefined
      ? "// Local module generated by Hirsh — wraps a custom (non-nf-core) tool.\n"
      : opts.header === null
        ? ""
        : `${opts.header}\n`;

  return `${headerComment}process ${proc} {
    tag "${hasMeta ? "$meta.id" : spec.name}"
    label '${label}'

${conda}${container}${noEnv}
    input:
${inputDecl(spec, hasMeta)}

    output:
${outputDecl(spec, hasMeta)}

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: ${prefixExpr}
    """
    ${spec.command}

    cat <<-END_VERSIONS > versions.yml
    "\${task.process}":
        ${spec.toolName}: \\$(${versionCmd})
    END_VERSIONS
    """

    stub:
    def prefix = task.ext.prefix ?: ${prefixExpr}
    """
${stubTouch}
    cat <<-END_VERSIONS > versions.yml
    "\${task.process}":
        ${spec.toolName}: \\$(${versionCmd})
    END_VERSIONS
    """
}
`;
}

/** Renders a minimal nf-core-style meta.yml for the local module. */
export function renderLocalMeta(spec: LocalToolSpec): string {
  const hasMeta = spec.hasMeta !== false;
  const inputEls = spec.inputs
    .map((io) => `      - ${io.name}:\n          type: ${io.type}`)
    .join("\n");
  const outputBlocks = spec.outputs
    .map(
      (o) =>
        `  - ${o.name}:\n${hasMeta ? "      - meta:\n          type: map\n" : ""}      - ${o.name}:\n          type: ${o.type}\n          pattern: "${o.pattern ?? "*"}"`,
    )
    .join("\n");
  return `name: "${spec.name}"
description: ${JSON.stringify(spec.description)}
keywords: []
tools:
  - "${spec.toolName}":
      description: ${JSON.stringify(spec.description)}
input:
  - -${hasMeta ? " meta:\n          type: map\n" : ""}${inputEls}
output:
${outputBlocks}
  - versions:
      - "versions.yml":
          type: file
          pattern: "versions.yml"
`;
}

/** Adapts a local tool spec into the NfCoreModule shape so wiring can place it. */
export function toNfCoreModule(spec: LocalToolSpec): NfCoreModule {
  const hasMeta = spec.hasMeta !== false;
  const inputElements = [
    ...(hasMeta ? [{ name: "meta", type: "map" }] : []),
    ...spec.inputs.map((io) => ({ name: io.name, type: io.type })),
  ];
  const outputs = spec.outputs.map((o) => ({
    name: o.name,
    elements: [
      ...(hasMeta ? [{ name: "meta", type: "map" }] : []),
      { name: o.name, type: o.type },
    ],
  }));
  outputs.push({ name: "versions", elements: [{ name: "versions", type: "file" }] });
  return {
    name: spec.name,
    path: `modules/local/${spec.name}`,
    description: spec.description,
    keywords: [],
    tools: [{ name: spec.toolName, description: spec.description }],
    inputs: [{ elements: inputElements }],
    outputs,
    local: true,
  };
}

function sanitizeName(name: string): string {
  const clean = name.toLowerCase().replace(/[^a-z0-9_]/g, "");
  return clean.length >= 2 ? clean : "customtool";
}

/**
 * Interactively gathers a custom tool spec from the scientist. Kept small: name,
 * environment (container/conda), command, one primary input and one output.
 */
export async function collectLocalTool(io: AgentIO): Promise<LocalToolSpec | null> {
  const rawName = (await io.ask("Short name for your tool (lowercase, e.g. 'myfilter'):")).trim();
  if (!rawName) return null;
  const name = sanitizeName(rawName);

  const description =
    (await io.ask("One-line description of what it does:")).trim() || `Custom tool ${name}.`;

  const container = (await io.ask("Container image (e.g. biocontainers/…; blank if none):")).trim();
  const conda = container
    ? ""
    : (await io.ask("Conda package (e.g. bioconda::samtools=1.19; blank if none):")).trim();

  const inputKind = (await io.ask("What does it take as input? (e.g. bam, reads, vcf):")).trim() || "input";
  const command =
    (await io.ask("Shell command to run (use $prefix for the output base, $args for extra args):")).trim() ||
    `echo "TODO: run ${name}" > ${"${prefix}"}.out`;
  const outKind = (await io.ask("What does it produce? (kind, e.g. bam, tsv):")).trim() || "output";
  const pattern =
    (await io.ask(`Output file pattern (e.g. *.${outKind}) [*.${outKind}]:`)).trim() || `*.${outKind}`;
  const versionCommand = (await io.ask("Command that prints the tool version (blank to skip):")).trim();

  return {
    name,
    toolName: name,
    description,
    command,
    container: container || undefined,
    conda: conda || undefined,
    inputs: [{ name: inputKind, type: "file" }],
    outputs: [{ name: outKind, type: "file", pattern }],
    versionCommand: versionCommand || undefined,
    hasMeta: true,
    label: "process_single",
  };
}
