/**
 * Executor abstraction (Phase 3).
 *
 * Beyond *what* runs and *how* (container/conda backend), Hirsh decides *where*
 * jobs run: on this machine, on an HPC scheduler (Slurm/SGE/LSF/PBS) or in the
 * cloud (AWS Batch). Rather than depend on a matching nf-core institutional
 * profile existing, Hirsh writes a small Nextflow config that sets
 * `process.executor` (+ queue) and passes it with `-c`, which works with any
 * pipeline.
 *
 * The config generation is pure (settings in, config text out) so it can be
 * unit-tested; the interactive selection is separated out.
 */
import type { AgentIO, ChoiceOption } from "../conversation/io.js";
import { chooseWith } from "../conversation/choice.js";
import type { ExecutorName } from "../config/types.js";

export interface ExecutorInfo {
  name: ExecutorName;
  label: string;
  /** Nextflow `process.executor` id (undefined for local — the default). */
  nextflowExecutor?: string;
  /** Whether a queue/partition is typically required. */
  needsQueue: boolean;
  /** Cloud executor (needs a work bucket + region). */
  cloud?: boolean;
  note: string;
}

export const EXECUTORS: Record<ExecutorName, ExecutorInfo> = {
  local: {
    name: "local",
    label: "Local machine",
    needsQueue: false,
    note: "Runs on this computer — good for tests and small jobs.",
  },
  slurm: {
    name: "slurm",
    label: "Slurm",
    nextflowExecutor: "slurm",
    needsQueue: true,
    note: "Submits jobs to a Slurm cluster (sbatch).",
  },
  sge: {
    name: "sge",
    label: "SGE / Univa Grid Engine",
    nextflowExecutor: "sge",
    needsQueue: true,
    note: "Submits jobs to a (Son of) Grid Engine cluster (qsub).",
  },
  lsf: {
    name: "lsf",
    label: "IBM LSF",
    nextflowExecutor: "lsf",
    needsQueue: true,
    note: "Submits jobs to an LSF cluster (bsub).",
  },
  pbs: {
    name: "pbs",
    label: "PBS / Torque",
    nextflowExecutor: "pbs",
    needsQueue: true,
    note: "Submits jobs to a PBS/Torque cluster (qsub).",
  },
  awsbatch: {
    name: "awsbatch",
    label: "AWS Batch",
    nextflowExecutor: "awsbatch",
    needsQueue: true,
    cloud: true,
    note: "Runs in the cloud on AWS Batch — needs a job queue and an S3 work directory.",
  },
};

export const EXECUTOR_ORDER: ExecutorName[] = ["local", "slurm", "sge", "lsf", "pbs", "awsbatch"];

export interface ExecutorSettings {
  executor: ExecutorName;
  /** Queue/partition name for cluster and cloud executors. */
  queue?: string;
  /** AWS region (awsbatch only). */
  awsRegion?: string;
  /** Nextflow work directory — must be an S3 path for awsbatch. */
  workDir?: string;
}

function quote(v: string): string {
  return `'${v.replace(/'/g, "\\'")}'`;
}

/**
 * Builds the Nextflow config (`-c` file) that selects the executor. Returns null
 * for the local executor, which needs no config.
 */
export function buildExecutorConfig(s: ExecutorSettings): string | null {
  if (s.executor === "local") return null;
  const info = EXECUTORS[s.executor];
  const lines: string[] = [
    "// Generated by Hirsh — execution backend (executor abstraction).",
    "process {",
    `    executor = ${quote(info.nextflowExecutor!)}`,
  ];
  if (s.queue) lines.push(`    queue = ${quote(s.queue)}`);
  lines.push("}");
  if (s.executor === "awsbatch") {
    if (s.awsRegion) lines.push(`aws.region = ${quote(s.awsRegion)}`);
    if (s.workDir) lines.push(`workDir = ${quote(s.workDir)}`);
  }
  return lines.join("\n") + "\n";
}

/** One-line human summary of the chosen executor for logs/provenance. */
export function describeExecutor(s: ExecutorSettings): string {
  if (s.executor === "local") return "local machine";
  const info = EXECUTORS[s.executor];
  const parts = [info.label];
  if (s.queue) parts.push(`queue "${s.queue}"`);
  if (s.executor === "awsbatch" && s.awsRegion) parts.push(`region ${s.awsRegion}`);
  return parts.join(", ");
}

/**
 * Short interactive executor selection. Presents the options, defaults to the
 * configured one, and gathers the queue (and, for AWS Batch, region + S3 work
 * directory) when needed.
 */
export async function chooseExecutor(
  io: AgentIO,
  configured: ExecutorName,
  defaultQueue?: string,
): Promise<ExecutorSettings> {
  // Recommended-options menu (arrow keys in a rich terminal; numbered otherwise).
  const options: ChoiceOption[] = EXECUTOR_ORDER.map((name) => ({
    value: name,
    label: EXECUTORS[name].label,
    description: EXECUTORS[name].note,
    recommended: name === configured,
  }));
  const picked = await chooseWith(io, "Where should the pipeline run?", options, {
    allowCustom: false,
  });
  const executor: ExecutorName = (EXECUTOR_ORDER as string[]).includes(picked)
    ? (picked as ExecutorName)
    : configured;

  const info = EXECUTORS[executor];
  const settings: ExecutorSettings = { executor };

  if (info.needsQueue) {
    const prompt = defaultQueue
      ? `Queue/partition name [${defaultQueue}]`
      : "Queue/partition name (leave blank to use the cluster default)";
    const q = (await io.ask(prompt)).trim();
    settings.queue = q || defaultQueue || undefined;
  }

  if (executor === "awsbatch") {
    const region = (await io.ask("AWS region (e.g. eu-west-1)")).trim();
    if (region) settings.awsRegion = region;
    const workDir = (await io.ask("S3 work directory (e.g. s3://my-bucket/work)")).trim();
    if (workDir) settings.workDir = workDir;
    if (!settings.workDir) {
      io.warn(
        "AWS Batch needs an S3 work directory; without one the run will fail. " +
          "You can set it later with `-work-dir s3://…`.",
      );
    }
  }

  return settings;
}
