/**
 * Reproducibility bundle (Phase 2).
 *
 * After a run is executed (or prepared), Hirsh writes a machine-readable
 * `run_manifest.json` and a plain-language `PROVENANCE.md` into the run
 * directory, so the scientist can archive, share or reproduce exactly what was
 * done. Building/rendering are pure (data in, strings out) for testing; only
 * writeProvenance touches disk.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { QueryContext } from "../conversation/session.js";
import type { MachineResources } from "./resources.js";

export interface RunManifest {
  tool: "hirsh";
  createdAt: string;
  pipeline: { name: string; revision: string };
  query: QueryContext;
  command: string;
  paramsFile?: string;
  params: Record<string, string | number | boolean>;
  samplesheet?: string;
  outdir?: string;
  environment: {
    nextflow?: string;
    containerEngine: string;
    os: string;
    arch: string;
    cpus: number;
    memoryGB: number;
  };
  llm: string;
  execution: { executed: boolean; exitCode?: number };
}

export interface ManifestInput {
  pipelineName: string;
  revision: string;
  query: QueryContext;
  /** The `nextflow run ...` argument list (without the leading "nextflow"). */
  command: string[];
  paramsFile?: string;
  params: Record<string, string | number | boolean>;
  samplesheet?: string;
  outdir?: string;
  nextflowVersion?: string;
  containerEngine: string;
  machine: MachineResources;
  llmLabel: string;
  executed: boolean;
  exitCode?: number;
  /** Defaults to now; injectable for deterministic tests. */
  createdAt?: string;
}

export function buildManifest(input: ManifestInput): RunManifest {
  return {
    tool: "hirsh",
    createdAt: input.createdAt ?? new Date().toISOString(),
    pipeline: { name: input.pipelineName, revision: input.revision },
    query: input.query,
    command: `nextflow ${input.command.join(" ")}`,
    paramsFile: input.paramsFile,
    params: input.params,
    samplesheet: input.samplesheet,
    outdir: input.outdir,
    environment: {
      nextflow: input.nextflowVersion,
      containerEngine: input.containerEngine,
      os: process.platform,
      arch: process.arch,
      cpus: input.machine.cpus,
      memoryGB: input.machine.memoryGB,
    },
    llm: input.llmLabel,
    execution: { executed: input.executed, exitCode: input.exitCode },
  };
}

/** Renders a human-readable provenance record for someone non-technical. */
export function renderProvenanceMarkdown(m: RunManifest): string {
  const q = m.query;
  const paramLines = Object.entries(m.params)
    .map(([k, v]) => `- \`${k}\`: ${v}`)
    .join("\n");
  const status = m.execution.executed
    ? m.execution.exitCode === 0
      ? "completed successfully"
      : `failed (exit code ${m.execution.exitCode})`
    : "prepared but not executed";

  return `# Provenance — ${m.pipeline.name}

Generated by Hirsh on ${m.createdAt}.

## What was run
- **Pipeline:** ${m.pipeline.name} (revision ${m.pipeline.revision})
- **Objective:** ${q.objective ?? "—"}
- **Organism:** ${q.organism ?? "—"}
- **Data type:** ${q.dataType ?? "—"}
- **Experimental design:** ${q.experimentalDesign ?? "—"}
- **Status:** ${status}

## Command
\`\`\`bash
${m.command}
\`\`\`

## Inputs & parameters
- **Samplesheet:** ${m.samplesheet ?? "—"}
- **Output directory:** ${m.outdir ?? "—"}
- **Parameter file:** ${m.paramsFile ?? "—"}
${paramLines || "- (none)"}

## Environment
- **Nextflow:** ${m.environment.nextflow ?? "—"}
- **Container engine:** ${m.environment.containerEngine}
- **Machine:** ${m.environment.cpus} CPUs, ${m.environment.memoryGB} GB RAM, ${m.environment.os}/${m.environment.arch}
- **LLM:** ${m.llm}

## Reproduce
From the run directory, re-running the command above reproduces this analysis
(the pinned revision and \`params.yaml\` fix the pipeline version and settings).
`;
}

export interface ProvenancePaths {
  manifest: string;
  markdown: string;
}

/** Writes run_manifest.json + PROVENANCE.md into the run directory. */
export function writeProvenance(runDir: string, manifest: RunManifest): ProvenancePaths {
  const manifestPath = join(runDir, "run_manifest.json");
  const markdownPath = join(runDir, "PROVENANCE.md");
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  writeFileSync(markdownPath, renderProvenanceMarkdown(manifest), "utf8");
  return { manifest: manifestPath, markdown: markdownPath };
}
